# Generated by Django 5.2.3 on 2025-07-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(upload_to='etudiants/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classe.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ecole')),
            ],
        ),
    ]
